name: flutter_cast_video
description: flutter_cast_video let you discover cast devices like Chrome Cast and Apple TV and connect to them.
version: 1.2.1
homepage: https://github.com/whowillcare/flutter_cast_video

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ^3.19.5

dependencies:
  flutter:
    sdk: flutter

  stream_transform: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: it.aesys.flutter_cast_video
        pluginClass: FlutterVideoCastPlugin
      ios:
        pluginClass: FlutterVideoCastPlugin
